main/urls.py
from django.urls import path

from main import views

app_name='main'
urlpatterns = [
    path("index/", views.index,name='index'),
    path("login/", views.login_form,name='login'),
    path("get_code/", views.get_code),
    path("check_user/", views.check_user),
]

main/views.py
from django.http import HttpResponse
from django.shortcuts import render
from redis import Redis
from utils.send import YunPian
from cmfz_193 import settings
import re
from rbacapp.models import UserInfo

red = Redis(host='127.0.0.1',port=6379)
red.set('name','666',10)

# Create your views here.
from django.views.decorators.csrf import csrf_exempt

from cmfz_193.settings import API_KEY
from utils.send import YunPian


def index(request):
    return render(request, "main.html")


def login_form(request):
    return render(request, "login.html")


@csrf_exempt
def get_code(request):
    """
    接受前端发送的ajax请求并为手机号发送验证码
    :param request: 用户输入的数据号
    :return: None
    """
    mobile = request.POST.get("mobile")
    MOBILE = "^1[358]\d{9}$|^147\d{8}$|^179\d{8}$"
    p = re.compile(MOBILE)

    if p.match(mobile):
        yun_pian = YunPian(settings.API_KEY)
        yun_pian.send_message(mobile)

        return HttpResponse("success")
    return HttpResponse("over")

    # 获取手机号有没有对应的验证码 查看验证码是否在120S内  如果在  提示验证码已经发送
    # value = redis.get("18500230996_1")  如果返回的值存在  代表120s之内还不能发送

    # 判断手机号是否存在  正则验证是否合法
    # if mobile:
    #     yun_pian = YunPian(API_KEY)
    #     yun_pian.send_message(mobile)
        # 将手机号与对应的验证码存入redis  防止无限制发送
        # redis.set("18500230996_1", "666666", 120S)
        # 保证验证码的有效期
        # redis.set("18500230996_2", "666666", 600s)



def check_user(request):
    """
    用户登录信息校验的视图
    :param request: 表单数据
    :return:
    """
    mobile = request.GET.get('mobile')
    code = request.GET.get('code')
    # 获取用户名
    username=request.GET.get('username')
    password=request.GET.get('password')

    result=UserInfo.objects.filter(name=username,password=password)[0]


    # if  red.get(mobile+'_1'):
    #     if str(red.get(mobile+'_1'),encoding='utf-8')==code:

    #         return HttpResponse('success')
    # return HttpResponse('over')
    if result:
        urls=result.roles.filter(permissions__isnull=False).values("permissions__url","permissions__is_menu",'permissions__title','permissions__id').distinct()
        url_list=[url['permissions__url'] for url in urls]
        menu_list=[] #存放菜单url
        for url in urls:
            print(url['permissions__title'])
            if url['permissions__is_menu']:
                temp={
                    'title':url['permissions__title'],
                    'id':url['permissions__id'],
                    'url':url['permissions__url'],

                }
                menu_list.append(temp)
        print(menu_list)
        request.session['url_list']=url_list      #所有权限列表
        request.session['menu_list']=menu_list    #该用户具备的菜单权限
        return HttpResponse('success')
    else:
        return HttpResponse('over')



    # 校验信息是否合法
    # 验证码是否在有效期内  使用redis
    # redis.get("18500230996_2")

templates/echars.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
</html>

templates/kindeditor.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="{% static 'kindeditor/kindeditor-all-min.js' %}"></script>
    <script src="{% static 'kindeditor/lang/zh-CN.js' %}"></script>
    <script>
        KindEditor.ready(function (K) {
            window.editor = K.create('#editor_id',{
                width:"900px",
                allowFileManager:true,
                fileManagerJson:'/artapp/get_all_img/',
                uploadJson:'/artapp/art_img/'
            });
        });
    </script>
</head>
<body>
<textarea id="editor_id" name="content" style="width:700px;height:300px;">
aaa
</textarea>
</body>
</html>

templates/load_earth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>商品后台管理系统</title>
    <link rel="stylesheet" href="{% static 'boot/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'jqgrid/css/trirand/ui.jqgrid-bootstrap.css' %}">
    <script src="{% static 'boot/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'boot/js/bootstrap.min.js' %}"></script>

    <!--发送按钮倒计时代码-->
    <script type="text/javascript">


        var countdown = 60;

        function settime(obj) {

            if (countdown == 0) {
                obj.removeAttribute("disabled");
                obj.value = "免费获取验证码";
                countdown = 60;
                return;
            } else {
                    var phone=$("#mobile").val()

                 var myreg=/^[1][3,4,5,7,8][0-9]{9}$/;
                    if(myreg.test(phone)){
                obj.setAttribute("disabled", true);
                obj.value = "重新发送(" + countdown + ")";
                countdown--}
            }
            setTimeout(function () {
                    settime(obj)
                }
                , 1000)
        }

        $(function () {
            $("#forcode").click(function () {
                // 根据用户输入的手机号发送验证码
                var phone=$("#mobile").val()

                 var myreg=/^[1][3,4,5,7,8][0-9]{9}$/;
                    if(myreg.test(phone)){

                        $.ajax({
                    type: 'post',
                    data: {mobile: phone},
                    url: "/main/get_code/",
                    success: function (data) {
                        if(data==="success"){
                            alert('验证码已发送')
                        }else{
                            alert('验证码发送失败')
                        }
                    }
                });
                    }else{
                        alert("手机号格式不对")

                    }

            });

            // 验证表单数据是否合法
            $("#loginButtonId").click(function () {

                $.ajax({
                    url: "/main/check_user/",
                    datatype: 'json',
                    type: 'get',
                    // 获取id为loginForm的表单数据
                    data: $("#loginForm").serialize(),
                    success: function (data) {
                        // g根据返回值判断是否登录成功  成功则跳转到首页
                        if(data==="success"){
                            location.href="{% url 'main:index' %}"
                        }else{

                            alert(data)
                        }
                    }
                });
            });
        });


    </script>

</head>


<body>

<!--手机号码输入框代码-->
<div class="container">
    <div class="form-group">
        <div class="col-lg-10">
            <form id="loginForm" role="form" action="" method="post" class="form-horizontal">

                <label for="mobile" class="">手机号码:</label>
                <div class="input-group m-bot15">
                    <input type="text" class="form-control" required id="mobile" name="mobile" placeholder="手机号码">
                    <span class="input-group-btn">
                         <input type="button" id="forcode" onclick="settime(this)" value="免费获取验证码"
                                class="btn btn-success">
                        </span>
                </div>
                <span id="msgDiv"></span>
                <p class="help-block">请填写绑定手机号</p>
                <label for="basic-url" class="">验证码：</label>
                <div class="input-group">
                    <input type="text" class="form-control" id="basic-url" required name="code">
                </div>

                <label for="basic-url" class="">账号：</label>
                <div class="input-group">
                    <input type="text" class="form-control" id="username" required name="username">
                </div>

                <label for="basic-url" class="">密码：</label>
                <div class="input-group">
                    <input type="text" class="form-control" id="password" required name="password">
                </div>

                <p class="help-block"></p>
                <div class="input-group">
                    <input class="btn btn-success" type="button" id="loginButtonId" value="登录">
                </div>
            </form>
        </div>
    </div>
</div>

</body>
</html>

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>商品后台管理系统</title>
    <link rel="icon" href="{% static 'img/arrow-up.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'boot/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'boot/css/back.css' %}">
    <link rel="stylesheet" href="{% static 'jqgrid/css/trirand/ui.jqgrid-bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'jqgrid/css/jquery-ui.css' %}">
    <script src="{% static 'boot/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'boot/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'jqgrid/js/trirand/src/jquery.jqGrid.js' %}"></script>
    <script src="{% static 'jqgrid/js/trirand/i18n/grid.locale-cn.js' %}"></script>
    <script src="{% static 'echars/js/echarts.min.js' %}"></script>
    <script src="{% static 'echars/js/china.js' %}"></script>
    <script src="{% static 'kindeditor/kindeditor-all-min.js' %}"></script>
    <script src="{% static 'kindeditor/lang/zh-CN.js' %}"></script>
</head>
<body>
<!--顶部导航-->
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!--导航标题-->
        <div class="navbar-header">
            <a href="javascript:location.reload(true);" class="navbar-brand">持名法州管理系统</a>
        </div>
        <!--导航内容-->
        <ul class="nav navbar-nav navbar-right">
            <li><a>欢迎:
            </a></li>
            <li><a href="">退出登录 <span class="glyphicon glyphicon-log-out"></span></a>
            </li>
        </ul>
    </div>
</nav>

<!--栅格系统-->
<div class="container-fluid">
    <div class="row">
        <!--左边-->
        <div class="col-xs-2">
            <div class="panel-group" id="accordion">
                <!--用户菜单-->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <a href="#aa" data-toggle="collapse" data-parent="#accordion"><h4>用户管理</h4></a>
                        </div>
                    </div>

                    <div id="aa" class="panel-collapse collapse ">
                        <div class="panel-body">
                            {% for url in request.session.menu_list %}
                            <ul class="nav nav-pills nav-stacked">
                                <li><a href="Javascript:$('#centerLayout').load('/static/static_html/'+'user.html')">{{ url.title }}</a></li>
{#                                <li><a href="Javascript:$('#centerLayout').load('{% static "static_html/map1.html" %}')">用户七天注册用户量</a></li>#}
{#                                <li><a href="Javascript:$('#centerLayout').load('{% static "static_html/earth.html" %}')">用户全国分布图</a></li>#}
                            </ul>
                            {% endfor %}
                        </div>
                    </div>

                    <div id="aa" class="panel-collapse collapse">
                        <div class="panel-body">
                            <ul class="nav nav-pills nav-stacked">

                            </ul>
                        </div>
                    </div>
                </div>

                <!--文章管理-->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <a href="#dds" data-toggle="collapse" data-parent="#accordion"><h4>文章管理</h4></a>
                        </div>
                    </div>

                    <div id="dds" class="panel-collapse collapse ">
                        <div class="panel-body">
                            <ul class="nav nav-pills nav-stacked">
                                <li><a href="Javascript:$('#centerLayout').load('{% static "static_html/kind.html" %}')">文章列表</a></li>
                            </ul>
                        </div>
                    </div>

                    <div id="dds" class="panel-collapse collapse ">
                        <div class="panel-body">
                            <ul class="nav nav-pills nav-stacked">
                            </ul>
                        </div>
                    </div>
                </div>
                <!--专辑管理-->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <a href="#ddd" data-toggle="collapse" data-parent="#accordion"><h4>专辑管理</h4></a>
                        </div>
                    </div>

                    <div id="ddd" class="panel-collapse collapse ">
                        <div class="panel-body">
                            <ul class="nav nav-pills nav-stacked">
                                <li><a href="Javascript:$('#centerLayout').load('{% static "static_html/album.html" %}')">专辑列表</a></li>
                            </ul>
                        </div>
                    </div>

                    <div id="dd" class="panel-collapse collapse ">
                        <div class="panel-body">
                            <ul class="nav nav-pills nav-stacked">

                            </ul>
                        </div>
                    </div>
                </div>

                <!--高级管理员-->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <a href="#gg" data-toggle="collapse" data-parent="#accordion"><h4>高级管理员</h4></a>
                        </div>
                    </div>
                    <div id="gg" class="panel-collapse collapse ">
                        <div class="panel-body">
                            <ul class="nav nav-pills nav-stacked">
                                <li><a href="Javascript:$('#centerLayout').load('{% static "static_html/banner.html" %}')">低级管理员列表</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!--轮播图管理-->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <a href="#cc" data-toggle="collapse" data-parent="#accordion"><h4>轮播图管理</h4></a>
                        </div>
                    </div>
                    <div id="cc" class="panel-collapse collapse ">
                        <div class="panel-body">
                            <ul class="nav nav-pills nav-stacked">
                                <li><a href="Javascript:$('#centerLayout').load('{% static "static_html/banner.html" %}')">轮播图列表</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <!--右边-->
        <div class="col-xs-10" id="centerLayout">
            <!--巨幕-->
            <div class="jumbotron">
                <h2 style="color:#898080;">欢迎来到持名法州后台管理系统</h2>
            </div>
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

                <div class="carousel-inner" role="listbox">
                    <div class="item active">
                        <img src="{% static 'img/shouye.jpg' %}" alt="..." style="height: 60%;width: auto">
                        <div class="carousel-caption">
                            ...
                        </div>
                    </div>
                    <div class="item">
                        <img src="{% static 'img/shouye.jpg' %}" alt="..." style="height: 60%;width: auto">
                        <div class="carousel-caption">
                        </div>
                    </div>
                    <div class="item">
                        <img src="{% static 'img/shouye.jpg' %}" alt="..." style="height: 60%;width: auto">
                        <div class="carousel-caption">
                        </div>
                    </div>
                </div>
                <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

        </div>

    </div>
</div>
<br/>
<div class="panel-footer">
    <div class="panel-title">
        <h5 style="text-align: center">@百知教育 baizhi@zparkhr.com.cn</h5>
    </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content" style="width:750px">
            <!--模态框标题-->
            <div class="modal-header">
                <!--
                    用来关闭模态框的属性:data-dismiss="modal"
                -->
                <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button>
                <h4 class="modal-title">编辑文章信息</h4>
            </div>

            <!--模态框内容体-->
            <div class="modal-body">
                <form action="//" class="form-horizontal"
                      id="addArticleFrom">
                    <div class="form-group">
                        <label class="col-sm-1 control-label">标题</label>
                        <div class="col-sm-5">
                            <input type="text" name="title" id="title" placeholder="请输入标题" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-1 control-label">分类</label>
                        <div class="col-sm-5">
                            <select class="form-control" name="status" id="status">
                                <option value="1">上师言教</option>
                                <option value="2">显密法要</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12">
                                            <textarea id="editor_id" name="content" style="width:700px;height:300px;">

                                            </textarea>
                        </div>
                    </div>
                    <input id="addInsertImg" name="insertImg" hidden>
                </form>
            </div>
            <!--模态页脚-->
            <div class="modal-footer" id="modal_footer">
                    <p>嘿嘿</p>
            </div>
        </div>
    </div>
</div>






</body>
</html>

templates/register.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .line>div{
            float: left;
        }
        .line,.register{
            clear: both;
        }
        .tt{
            width: 1000px;
            height: 25px;
        }
        .div1{
            width: 200px;
            height: 25px;
        }
        .div2{
            width: 300px;
            height: 25px;
        }
        *{
            font-size: 14px;
            color: #999;
        }
        span{
            background: #eee;
        }
        .register{
            border: 1px solid #f00;
            position: relative;
            top: 1px;
            left: 200px;
            background: #e3393c;
            width: 150px;
            height: 40px;
            line-height: 40px;
            text-align: center;
            border-radius: 6px;
            font-size: 16px;
            color: white;
        }
    </style>
</head>
<body>
<div class="tt">
    <div class="line">
        <div class="div1">用户名:</div>
        <div class="div2"><input type="text"></div>
        <div class="div3">4-20位字符，不支持汉字，支持字母和数字组合</div>

    </div>
    <div class="line">
        <div class="div1">请设置密码:</div>
        <div class="div2"><input type="text"></div>
        <div class="div3">6-20位字符，不支持汉字，支持字母和数字组合</div>
    </div>
    <div class="line">
        <div class="div1">请确认密码:</div>
        <div class="div2"><input type="text"></div>
        <div class="div3">请再次输入密码</div>
    </div>
    <div class="line">
        <div class="div1">验证手机:</div>
        <div class="div2"><input type="text"></div>
        <div class="div3">完成设置后可以用手机找回密码</div>
    </div>
    <div class="line">
        <div class="div1">短信验证码:</div>
        <div class="div2"><input type="text"style="width: 100px"><input type="button" value="获取验证码"></input></div>   # 灵活运用button按钮
        <div class="div3">请输入短信验证码 </div>
    </div>
    <div class="register">
         立即注册
    </div>
</div>
</body>
</html>